### ISSUE TITLE
Perl

### ISSUE THREAD

**Issue by AmitaCM** [bioperl/bioperl-run#56] opened 2018-08-15 14:53 UTC
THIS CODE IS NOT WORKING Showing directory or file not foun, Please help

$s = "agcttataatcgtacgtacgtacgtacgtacgtaccccggggtttt";
if ($s=~m/(tataat)/)
{
print "$1found\n";
}
else 
{
print "tataat not found";
}

use LWP qw(C:\Perl\site\lib\LWP);
use LWP qw(C:\Perl\lib\LWP);
$url = "https://www.ncbi.nlm.nih.gov/nuccore/AABQ01000377.1?report=genbank";
$content = get $url;
print $content;

**Comment by carandraug** [comment] 2018-08-16 00:53
This is not a help forum for help on bioformats using bioperl. This is a tracker for issues of the project bioperl-run. Closing this as invalid / not a bug.

**Closed by carandraug** 2018-08-16 00:53 UTC
